// Primitive + Era 2 + Era 3 tool definitions — DATA, not code.

export const TOOL_CATEGORIES = {
  primitive:  { id: "primitive",  name: "Primitive",  order: 1 },
  bronze:     { id: "bronze",     name: "Bronze",     order: 2 },
  iron:       { id: "iron",       name: "Iron",       order: 3 },
  arcane:     { id: "arcane",     name: "Arcane",     order: 4 },
  alchemy:    { id: "alchemy",    name: "Alchemy",    order: 4.5 },
  consumable: { id: "consumable", name: "Potions",    order: 5 },
};

export const TOOLS = {
  net: {
    id: "net", name: "Net", icon: "🕸️", category: "primitive",
    description: "A loose weave of cordage and lashings. Throw it; pray.",
    cost: { wood: 6, stone: 2 },
    requires: { researched: "netWeaving" },
    effect: { unlocksAction: "hunt" },
    durability: { max: 6, wearsOn: "hunt" },
    effectSummary: "Unlocks the Hunt action. · 6 hunts before it frays.",
    onCraftedMessage: "🕸️ You finish the net. The lashings hold.",
    onBrokenMessage: "🕸️ The net comes apart in your hands.",
    tier: 1, col: 0,
  },

  snare: {
    id: "snare", name: "Snare", icon: "🪤", category: "primitive",
    description: "A loop of cordage hidden where birds land.",
    cost: { wood: 8, stone: 3, feathers: 2 },
    requires: { researched: "trapping", skill: { hunting: 2 } },
    effect: { huntYieldBonus: 1, huntCooldownReduction: 1500, huntBetterBirds: 4 },
    durability: { max: 10, wearsOn: "hunt" },
    effectSummary: "+1 hunt yield · -1500ms hunt cooldown · 10 hunts.",
    onCraftedMessage: "🪤 The snare is set.",
    onBrokenMessage: "🪤 The snare line snaps.",
    tier: 1, col: 1,
  },

  diggingStick: {
    id: "diggingStick", name: "Digging Stick", icon: "🥢", category: "primitive",
    description: "A hardwood shaft, fire-tempered.",
    cost: { wood: 5, stone: 2 },
    requires: { researched: "diggingStickCraft" },
    effect: { gatherSpeedup: 100, waterBonus: 1 },
    durability: { max: 12, wearsOn: "gather" },
    effectSummary: "-100ms gather · +1 water on water gathers · 12 gathers.",
    onCraftedMessage: "🥢 You shape the stick and harden the tip.",
    onBrokenMessage: "🥢 The tip splinters and snaps off.",
    tier: 1, col: 2,
  },

  waterSkin: {
    id: "waterSkin", name: "Water Skin", icon: "🧴", category: "primitive",
    description: "A bladder of stretched hide, sealed with sap.",
    cost: { water: 3, feathers: 1, stone: 1 },
    requires: { researched: "waterCarrying" },
    effect: { waterBonus: 1 },
    durability: { max: 15, wearsOn: "waterGather" },
    effectSummary: "+1 water on water gathers · 15 water-fills.",
    onCraftedMessage: "🧴 You stitch and seal. The skin holds.",
    onBrokenMessage: "🧴 The seal gives way.",
    tier: 1, col: 3,
  },

  // DUAL-USE: hatchet pattern — wood-leaning. Modest combat stats so the
  // player can wield it if needed (subfamily axe; battle axe variant in
  // Phase 5 trades wood-yield for damage). See content/weapons.js for
  // the subfamily pattern.
  stoneAxe: {
    id: "stoneAxe", name: "Stone Axe", icon: "🪓", category: "bronze",
    subfamily: "axe",
    description: "A shaped stone bound to a hardwood haft. The trees give up wood twice as easily now. Wielded, it does its uglier work.",
    cost: { wood: 15, stone: 20 },
    requires: { researched: "smithing", builtBuilding: "forge" },
    effect: { gatherSpeedup: 150, woodBonus: 2 },
    // Combat (Task #33 reads this): hatchet-leaning. Decent damage band,
    // moderate accuracy, low crit. A worse battle axe by design.
    weaponStats: { type: "melee", damage: [3, 6], acc: 0.7, crit: 0.04 },
    durability: { max: 35, wearsOn: "gather" },
    effectSummary: "-150ms gather · +2 wood on wood gathers · 35 gathers. Wieldable: 3-6 dmg.",
    onCraftedMessage: "🪓 The axe head is bound. Weight in the hand. Edges that bite.",
    onBrokenMessage: "🪓 The axe head splits from the haft. Time to make another.",
    tier: 2, col: 0,
  },

  // DUAL-USE: pickaxe — stone-leaning. Bad as a weapon. The player CAN
  // wield it but the numbers won't reward them. War-pick variant in
  // Phase 5 (#36) trades stone-yield for damage.
  stonePickaxe: {
    id: "stonePickaxe", name: "Stone Pickaxe", icon: "⛏️", category: "bronze",
    subfamily: "pickaxe",
    description: "Heavy. Pointed. Made for breaking rock into more rock. Awkward to swing at anything else.",
    cost: { wood: 12, stone: 25 },
    requires: { researched: "smithing", builtBuilding: "forge" },
    effect: { gatherSpeedup: 100, stoneBonus: 2 },
    // Combat: heavy, slow, poor accuracy. Why would you? Mostly so the
    // player CAN if they have to. Numbers say: don't.
    weaponStats: { type: "melee", damage: [2, 5], acc: 0.55, crit: 0.02 },
    durability: { max: 35, wearsOn: "gather" },
    effectSummary: "-100ms gather · +2 stone on stone gathers · 35 gathers. Wieldable (poorly): 2-5 dmg.",
    onCraftedMessage: "⛏️ The pickaxe is whole. The earth's bones look softer now.",
    onBrokenMessage: "⛏️ The pick chips and breaks at the head.",
    tier: 2, col: 1,
  },

  // DUAL-USE: cooking knife pattern — food-leaning. Decent crit (it's a
  // knife). Dagger variant in Phase 5 trades food-bonus for damage + crit.
  boneKnife: {
    id: "boneKnife", name: "Bone Knife", icon: "🔪", category: "bronze",
    subfamily: "knife",
    description: "Sharpened femur, lashed to a stone grip. Better for skinning than swinging — but it'll bite when it has to.",
    cost: { stone: 10, feathers: 3, food: 5 },
    requires: { researched: "smithing", builtBuilding: "forge" },
    effect: { huntYieldBonus: 1, foodBonus: 1 },
    // Combat: high accuracy (it's a known shape in your hand), good crit
    // (sharp), low damage band (it's small).
    weaponStats: { type: "melee", damage: [2, 5], acc: 0.85, crit: 0.1 },
    durability: { max: 40, wearsOn: "hunt" },
    effectSummary: "+1 hunt yield · +1 food on food gathers · 40 hunts. Wieldable: 2-5 dmg, +crit.",
    onCraftedMessage: "🔪 The knife is keen. The bird gives up more meat under your hand now.",
    onBrokenMessage: "🔪 The blade chips and falls from the grip.",
    tier: 2, col: 2,
  },

  // DUAL-USE: ranged. The bow's combat role IS its hunt role — reach.
  // Goes in the ranged slot (`type: "ranged"`). Two-handed in narrative
  // but slot-system-wise it's a single ranged-slot equip.
  bow: {
    id: "bow", name: "Bow", icon: "🏹", category: "bronze",
    subfamily: "bow",
    description: "Curved wood, sinew strung. Reach is not strength — it's better.",
    cost: { wood: 20, feathers: 8, stone: 5 },
    requires: { researched: "fletching", builtBuilding: "forge" },
    effect: { huntCooldownReduction: 2500, huntYieldBonus: 2, huntBetterBirds: 8 },
    // Combat: ranged. High damage, good accuracy, modest crit.
    weaponStats: { type: "ranged", damage: [5, 9], acc: 0.8, crit: 0.05 },
    durability: { max: 40, wearsOn: "hunt" },
    effectSummary: "+2 hunt yield · -2500ms hunt cooldown · way more birds · 40 hunts. Ranged: 5-9 dmg.",
    onCraftedMessage: "🏹 The bow is finished. You draw, release. The arrow flies. Something far falls.",
    onBrokenMessage: "🏹 The string snaps and the limb cracks. A bow's work is done.",
    tier: 2, col: 3,
  },

  // ===== Arcane tier (Era 3) =====

  // DUAL-USE arcane: a dagger that's also a great food-gather tool. Combat
  // stats are dagger-tier (high crit, decent acc) with arcane damage band.
  fragmentKnife: {
    id: "fragmentKnife", name: "Fragment Knife", icon: "🗡️", category: "arcane",
    subfamily: "knife",
    description: "A bone knife rebound. The blade is veined with shard, and the shard hums against the back of your skull when you draw it. The cut is cleaner. The cost is paid elsewhere.",
    cost: { fragments: 5, stone: 10, food: 5 },
    requires: { researched: "arcaneAwakening", builtBuilding: "forge" },
    effect: { huntYieldBonus: 2, foodBonus: 2, sanityPerFoodGather: -1 },
    weaponStats: { type: "melee", damage: [4, 8], acc: 0.88, crit: 0.15 },
    durability: { max: 100, wearsOn: "hunt" },
    effectSummary: "+2 hunt yield · +2 food on food gathers · -1 sanity per food gather (the blade hums) · 100 hunts. Wieldable: 4-8 dmg, high crit.",
    onCraftedMessage: "🗡️ The Fragment Knife is whole. Light bends along the edge.",
    onBrokenMessage: "🗡️ The shard inlay shatters. The blade goes quiet, then breaks.",
    tier: 3, col: 0,
  },

  spiritCenser: {
    id: "spiritCenser", name: "Spirit Censer", icon: "🪔", category: "arcane",
    description: "A small censer of cold metal. It does not burn anything. It hums faintly, and the air around it remembers what air used to feel like.",
    cost: { fragments: 8, stone: 15, water: 5 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic" },
    effect: { spiritPerMinute: 1 },
    effectSummary: "+1 Spirit / minute, passive while carried. No durability.",
    onCraftedMessage: "🪔 The Censer is finished. It hums when you carry it.",
    tier: 3, col: 1,
  },

  wardingTalisman: {
    id: "wardingTalisman", name: "Warding Talisman", icon: "🧿", category: "arcane",
    description: "A small carved disc on a cord. The eye watches the dark for you. The dark watches it back, and steps lighter.",
    cost: { fragments: 6, feathers: 5, stone: 10 },
    requires: { researched: "banishSpell", builtBuilding: "alembic" },
    effect: { demonDamageMult: 0.5, demonSanityMult: 0.5 },
    effectSummary: "Demons deal HALF damage AND half sanity drain. No durability.",
    onCraftedMessage: "🧿 The Talisman is bound. You can feel the air thin around it.",
    tier: 3, col: 2,
  },

  // ===== Arcane weapon roster (#114) — six Era-3 weapons that the
  // player can craft once arcaneAwakening is researched. Mix of melee,
  // ranged, two-handed, and apex-gated so combat builds have real
  // choices in the magic era. Each carries an arcane flavor: some hum
  // with shard, some drain Sanity, some feed on Spirit.

  fragmentBlade: {
    id: "fragmentBlade", name: "Fragment Blade", icon: "⚔️", category: "arcane",
    subfamily: "sword",
    description: "A two-handed sword forged around a vein of shard. Heavy in the hand — light in the cut. The blade hums in time with the wielder's heartbeat.",
    cost: { fragments: 12, stone: 25, wood: 10, shattered_glyph: 2 },
    requires: { researched: "arcaneAwakening", builtBuilding: "forge" },
    weaponStats: { type: "two-handed", damage: [8, 14], acc: 0.78, crit: 0.10 },
    durability: { max: 120, wearsOn: "combat" },
    effectSummary: "Two-handed melee. Dmg 8–14 · Acc 78% · Crit 10% · 120 swings.",
    onCraftedMessage: "⚔️ The Fragment Blade is whole. It hums against the shoulder.",
    onBrokenMessage: "⚔️ The shard inlay shatters. The blade goes silent, then snaps.",
    tier: 3, col: 6,
  },

  sigilStaff: {
    id: "sigilStaff", name: "Sigil Staff", icon: "🔮", category: "arcane",
    subfamily: "staff",
    discipline: "woodworking",
    description: "A length of hardwood inlaid with bone-etched sigils. The runes carry the spell the way water carries a leaf — without effort, in the right direction.",
    cost: { fragments: 8, wood: 25, ink: 4, shattered_glyph: 3 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic" },
    weaponStats: { type: "two-handed", damage: [6, 12], acc: 0.82, crit: 0.08, damageType: "magic", spiritCost: 2 },
    durability: { max: 100, wearsOn: "combat" },
    effectSummary: "Magic two-hander. Dmg 6–12 · Acc 82% · 2 Spirit / swing · 100 strikes.",
    onCraftedMessage: "🔮 The Sigil Staff is finished. The runes settle into their meaning.",
    onBrokenMessage: "🔮 The sigils flicker out. The staff is just wood again.",
    tier: 3, col: 7,
  },

  echoBow: {
    id: "echoBow", name: "Echo Bow", icon: "🏹", category: "arcane",
    subfamily: "bow",
    discipline: "fletching",
    description: "A bow strung with sinew that remembers being elsewhere. The arrow leaves twice — once when you release it, once when it strikes.",
    cost: { fragments: 10, wood: 20, feathers: 12, spirit_essence: 2 },
    requires: { researched: "arcaneAwakening", studied: "firstEcho", builtBuilding: "forge" },
    weaponStats: { type: "ranged", damage: [7, 13], acc: 0.86, crit: 0.12, spiritCost: 1 },
    durability: { max: 100, wearsOn: "combat" },
    effectSummary: "Ranged. Dmg 7–13 · Acc 86% · Crit 12% · 1 Spirit / shot · 100 shots.",
    onCraftedMessage: "🏹 The Echo Bow is strung. You draw once. You hear it draw twice.",
    onBrokenMessage: "🏹 The remembering string snaps. The bow forgets itself.",
    tier: 3, col: 8,
  },

  voidcallerWand: {
    id: "voidcallerWand", name: "Voidcaller Wand", icon: "⚫", category: "arcane",
    subfamily: "wand",
    discipline: "woodworking",
    description: "A short rod of stone the color of nothing. Holding it costs sanity. Using it costs more. What answers is glad to be called.",
    cost: { fragments: 15, stone: 20, ink: 6, void_bone: 3, shadow_dust: 2 },
    requires: { researched: "voidcall", builtBuilding: "alembic", alignment: { evil: 5 } },
    weaponStats: { type: "melee", damage: [10, 16], acc: 0.80, crit: 0.15, damageType: "magic", spiritCost: 3, sanityCost: 2 },
    durability: { max: 80, wearsOn: "combat" },
    effectSummary: "Off-hand magic. Dmg 10–16 · Crit 15% · 3 Spirit + 2 Sanity / swing · 80 strikes. The wand watches.",
    onCraftedMessage: "⚫ The Voidcaller Wand is shaped. It is colder than the room. It is waiting.",
    onBrokenMessage: "⚫ The wand goes dark — darker than it was. It is no longer yours.",
    tier: 3, col: 9,
  },

  stonespeakHammer: {
    id: "stonespeakHammer", name: "Stonespeak Hammer", icon: "🔨", category: "arcane",
    subfamily: "mace",
    description: "A great hammer cast from forge-iron, the haft wrapped in cord that hums when the wielder listens for it. Each strike speaks Stoneword.",
    cost: { fragments: 10, stone: 30, wood: 15, void_bone: 2 },
    requires: { researched: "arcaneAwakening", studied: "firstStoneword", builtBuilding: "forge" },
    weaponStats: { type: "two-handed", damage: [12, 18], acc: 0.70, crit: 0.05 },
    durability: { max: 140, wearsOn: "combat" },
    effectSummary: "Two-handed melee. Dmg 12–18 · Acc 70% · Crit 5% · 140 swings. Heaviest in the roster.",
    onCraftedMessage: "🔨 The Stonespeak Hammer is bound. The haft warms in the hand.",
    onBrokenMessage: "🔨 The head separates from the haft. The hammer was speaking. Now it isn't.",
    tier: 3, col: 10,
  },

  censerDagger: {
    id: "censerDagger", name: "Censer Dagger", icon: "🕯️", category: "arcane",
    subfamily: "knife",
    description: "A short blade with a hollow pommel that holds a small ember. Cuts breathe. The Spirit returns a little with each one that lands true.",
    cost: { fragments: 8, stone: 8, feathers: 4, spirit_essence: 1 },
    requires: { researched: "arcaneAwakening", builtBuilding: "forge" },
    weaponStats: { type: "melee", damage: [3, 7], acc: 0.92, crit: 0.20, spiritReturn: 1 },
    durability: { max: 90, wearsOn: "combat" },
    effectSummary: "Off-hand melee. Dmg 3–7 · Acc 92% · Crit 20% · +1 Spirit on hit · 90 strikes.",
    onCraftedMessage: "🕯️ The Censer Dagger is finished. The pommel warms in the hand.",
    onBrokenMessage: "🕯️ The pommel cracks; the ember winks out. The blade goes quiet.",
    tier: 3, col: 11,
  },

  // ===== Arcane blades / swords (#116) — second wave =====

  shardtoothSabre: {
    id: "shardtoothSabre", name: "Shardtooth Sabre", icon: "🩸", category: "arcane",
    subfamily: "sword",
    description: "A curved sabre lined with serrated shards. Cuts ragged; the wound remembers the cut for days.",
    cost: { fragments: 8, stone: 15, wood: 8 },
    requires: { researched: "arcaneAwakening", builtBuilding: "forge" },
    weaponStats: { type: "melee", damage: [7, 11], acc: 0.84, crit: 0.12 },
    durability: { max: 110, wearsOn: "combat" },
    effectSummary: "Melee. Dmg 7–11 · Acc 84% · Crit 12% · 110 swings.",
    onCraftedMessage: "🩸 The Shardtooth Sabre is whole. The teeth on the blade catch the light wrong.",
    onBrokenMessage: "🩸 The shards fall from the blade. The sabre is just metal again.",
    tier: 3, col: 12,
  },

  halflightFalchion: {
    id: "halflightFalchion", name: "Halflight Falchion", icon: "✦", category: "arcane",
    subfamily: "sword",
    description: "A short heavy blade with a sigil etched along the spine. In darkness the etching glows faintly. Demons notice it before they notice you.",
    cost: { fragments: 7, stone: 14, ink: 3 },
    requires: { researched: "arcaneAwakening", studied: "sanctuary", builtBuilding: "forge" },
    weaponStats: { type: "melee", damage: [6, 11], acc: 0.83, crit: 0.08, demonBonus: 0.3 },
    durability: { max: 105, wearsOn: "combat" },
    effectSummary: "Melee. Dmg 6–11 · Acc 83% · +30% vs demons · 105 swings.",
    onCraftedMessage: "✦ The Halflight Falchion is bound. The sigil settles when you hold it level.",
    onBrokenMessage: "✦ The sigil fades. The light goes with it.",
    tier: 3, col: 13,
  },

  lacunaRapier: {
    id: "lacunaRapier", name: "Lacuna Rapier", icon: "⚜️", category: "arcane",
    subfamily: "sword",
    description: "A narrow blade pierced with a vertical slit that the eye refuses to follow. Reads the gap in the opponent's stance the way water reads downhill.",
    cost: { fragments: 9, stone: 10, feathers: 6 },
    requires: { researched: "arcaneAwakening", builtBuilding: "forge" },
    weaponStats: { type: "melee", damage: [5, 9], acc: 0.95, crit: 0.18 },
    durability: { max: 100, wearsOn: "combat" },
    effectSummary: "Melee. Dmg 5–9 · Acc 95% · Crit 18% · 100 thrusts.",
    onCraftedMessage: "⚜️ The Lacuna Rapier is whole. The slit in the blade leads nowhere.",
    onBrokenMessage: "⚜️ The blade folds at the slit. The gap closes for good.",
    tier: 3, col: 14,
  },

  echocutShortsword: {
    id: "echocutShortsword", name: "Echocut Shortsword", icon: "🎴", category: "arcane",
    subfamily: "sword",
    description: "A short blade quenched in water that remembers being elsewhere. Each strike lands twice — once now, once a moment later.",
    cost: { fragments: 8, stone: 12, water: 8 },
    requires: { researched: "arcaneAwakening", studied: "firstEcho", builtBuilding: "forge" },
    weaponStats: { type: "melee", damage: [6, 10], acc: 0.87, crit: 0.10, echoChance: 0.2 },
    durability: { max: 100, wearsOn: "combat" },
    effectSummary: "Melee. Dmg 6–10 · Acc 87% · 20% chance to strike twice · 100 swings.",
    onCraftedMessage: "🎴 The Echocut is whole. You swing once. The air remembers.",
    onBrokenMessage: "🎴 The blade snaps. The echo doesn't.",
    tier: 3, col: 15,
  },

  soulrendGreatsword: {
    id: "soulrendGreatsword", name: "Soulrend Greatsword", icon: "🗡", category: "arcane",
    subfamily: "sword",
    description: "A two-handed sword forged for the work of unmaking. Drinks resolve from the wielder; pays it back in raw cut.",
    cost: { fragments: 14, stone: 28, wood: 12, corrupted_flesh: 3, shadow_dust: 2 },
    requires: { researched: "voidcall", builtBuilding: "forge", alignment: { evil: 3 } },
    weaponStats: { type: "two-handed", damage: [11, 17], acc: 0.74, crit: 0.10, sanityCost: 1 },
    durability: { max: 130, wearsOn: "combat" },
    effectSummary: "Two-handed. Dmg 11–17 · 1 Sanity / swing · 130 swings.",
    onCraftedMessage: "🗡 The Soulrend is whole. The weight is wrong — pleasantly wrong.",
    onBrokenMessage: "🗡 The blade fractures at the tang. The hunger leaves with it.",
    tier: 3, col: 16,
  },

  voidsplinterKnife: {
    id: "voidsplinterKnife", name: "Voidsplinter Knife", icon: "🖤", category: "arcane",
    subfamily: "knife",
    description: "A dagger ground from a single fragment of void-stone. Wounds it leaves go cold and stay cold. Bad for the wielder. Worse for the cut.",
    cost: { fragments: 10, stone: 6 },
    requires: { researched: "voidcall", builtBuilding: "forge", alignment: { evil: 4 } },
    weaponStats: { type: "melee", damage: [4, 9], acc: 0.90, crit: 0.25, sanityCost: 1 },
    durability: { max: 95, wearsOn: "combat" },
    effectSummary: "Off-hand. Dmg 4–9 · Crit 25% · 1 Sanity / swing · 95 strikes.",
    onCraftedMessage: "🖤 The Voidsplinter is shaped. The blade is colder than the room.",
    onBrokenMessage: "🖤 The fragment finally splinters. Something exhales.",
    tier: 3, col: 17,
  },

  mournwhisperDagger: {
    id: "mournwhisperDagger", name: "Mournwhisper Dagger", icon: "🪦", category: "arcane",
    subfamily: "knife",
    description: "A funeral knife. The pommel is bone wrapped in cord that was once a shroud.",
    cost: { fragments: 7, stone: 8, feathers: 4 },
    requires: { researched: "arcaneAwakening", studied: "ghostcall", builtBuilding: "forge" },
    weaponStats: { type: "melee", damage: [4, 8], acc: 0.93, crit: 0.20, sanityDamage: 2 },
    durability: { max: 95, wearsOn: "combat" },
    effectSummary: "Off-hand. Dmg 4–8 · Crit 20% · +2 sanity dmg to foe per hit · 95 strikes.",
    onCraftedMessage: "🪦 The Mournwhisper is bound. It does not gleam — it absorbs.",
    onBrokenMessage: "🪦 The cord unravels. The blade goes silent.",
    tier: 3, col: 18,
  },

  boneSigilDagger: {
    id: "boneSigilDagger", name: "Bone Sigil Dagger", icon: "🦴", category: "arcane",
    subfamily: "knife",
    description: "Carved sigils run the length of the bone-blade. The bone remembers being warm.",
    cost: { fragments: 6, stone: 4, feathers: 6, ink: 2 },
    requires: { researched: "arcaneAwakening", builtBuilding: "forge" },
    weaponStats: { type: "melee", damage: [3, 6], acc: 0.91, crit: 0.18, spiritReturn: 2 },
    durability: { max: 100, wearsOn: "combat" },
    effectSummary: "Off-hand. Dmg 3–6 · Acc 91% · +2 Spirit on hit · 100 strikes.",
    onCraftedMessage: "🦴 The Bone Sigil Dagger is finished. The carvings hum.",
    onBrokenMessage: "🦴 The bone splinters.",
    tier: 3, col: 19,
  },

  spiritsongLongbow: {
    id: "spiritsongLongbow", name: "Spiritsong Longbow", icon: "🎵", category: "arcane",
    subfamily: "bow", discipline: "fletching",
    description: "A tall yew bow strung with sinew that hums when drawn.",
    cost: { fragments: 9, wood: 25, feathers: 14 },
    requires: { researched: "arcaneAwakening", builtBuilding: "forge" },
    weaponStats: { type: "ranged", damage: [8, 14], acc: 0.84, crit: 0.10, spiritReturn: 1 },
    durability: { max: 105, wearsOn: "combat" },
    effectSummary: "Ranged. Dmg 8–14 · Acc 84% · +1 Spirit on hit · 105 shots.",
    onCraftedMessage: "🎵 The Spiritsong is strung. The note is low and right.",
    onBrokenMessage: "🎵 The string snaps. The note ends mid-phrase.",
    tier: 3, col: 20,
  },

  lightweaveBow: {
    id: "lightweaveBow", name: "Lightweave Bow", icon: "🔆", category: "arcane",
    subfamily: "bow", discipline: "fletching",
    description: "A shortbow strung with Light-path sigils. Demons feel them more.",
    cost: { fragments: 10, wood: 18, feathers: 10, ink: 3 },
    requires: { researched: "arcaneAwakening", studied: "blessing", builtBuilding: "forge" },
    weaponStats: { type: "ranged", damage: [6, 11], acc: 0.90, crit: 0.10, demonBonus: 0.4 },
    durability: { max: 95, wearsOn: "combat" },
    effectSummary: "Ranged. Dmg 6–11 · Acc 90% · +40% vs demons · 95 shots.",
    onCraftedMessage: "🔆 The Lightweave is whole. The sigils breathe with the draw.",
    onBrokenMessage: "🔆 The sigils unwind.",
    tier: 3, col: 21,
  },

  sigilShortbow: {
    id: "sigilShortbow", name: "Sigil Shortbow", icon: "✒️", category: "arcane",
    subfamily: "bow", discipline: "fletching",
    description: "A compact bow with sigils inked along the limb.",
    cost: { fragments: 7, wood: 15, feathers: 8, ink: 4 },
    requires: { researched: "arcaneAwakening", builtBuilding: "forge" },
    weaponStats: { type: "ranged", damage: [5, 10], acc: 0.92, crit: 0.14, damageType: "magic", spiritCost: 1 },
    durability: { max: 100, wearsOn: "combat" },
    effectSummary: "Ranged magic. Dmg 5–10 · Crit 14% · 1 Spirit / shot · 100 shots.",
    onCraftedMessage: "✒️ The Sigil Shortbow is finished.",
    onBrokenMessage: "✒️ The sigils smear.",
    tier: 3, col: 22,
  },

  bonelimbBow: {
    id: "bonelimbBow", name: "Bonelimb Bow", icon: "🍖", category: "arcane",
    subfamily: "bow", discipline: "fletching",
    description: "A bow built from a long curve of bone. Kills clean.",
    cost: { fragments: 5, wood: 12, feathers: 12, food: 8 },
    requires: { researched: "arcaneAwakening", builtBuilding: "forge", skill: { butchering: 5 } },
    weaponStats: { type: "ranged", damage: [7, 12], acc: 0.85, crit: 0.08, butcheryBonus: 0.2 },
    durability: { max: 110, wearsOn: "combat" },
    effectSummary: "Ranged. Dmg 7–12 · +20% butchery yield · 110 shots.",
    onCraftedMessage: "🍖 The Bonelimb is finished. The bone remembers being meat.",
    onBrokenMessage: "🍖 The bone splits down the grain.",
    tier: 3, col: 23,
  },

  memorywoodStaff: {
    id: "memorywoodStaff", name: "Memorywood Staff", icon: "🔔", category: "arcane",
    subfamily: "staff", discipline: "woodworking",
    description: "A staff cut from a tree that grew where a quiet grief had been.",
    cost: { fragments: 9, wood: 22, ink: 4 },
    requires: { researched: "arcaneAwakening", studied: "firstEcho", builtBuilding: "alembic" },
    weaponStats: { type: "two-handed", damage: [5, 11], acc: 0.84, crit: 0.06, damageType: "magic", spiritCost: 2, sanityReturn: 1 },
    durability: { max: 100, wearsOn: "combat" },
    effectSummary: "Magic two-hander. Dmg 5–11 · 2 Spirit / swing · +1 Sanity on hit · 100 strikes.",
    onCraftedMessage: "🔔 The Memorywood Staff is whole.",
    onBrokenMessage: "🔔 The staff splits along the grain.",
    tier: 3, col: 24,
  },

  stonewordCrozier: {
    id: "stonewordCrozier", name: "Stoneword Crozier", icon: "👂", category: "arcane",
    subfamily: "staff", discipline: "woodworking",
    description: "A long staff topped with a knot of polished river-stone.",
    cost: { fragments: 11, wood: 18, stone: 22 },
    requires: { researched: "arcaneAwakening", studied: "firstStoneword", builtBuilding: "alembic" },
    weaponStats: { type: "two-handed", damage: [9, 14], acc: 0.78, crit: 0.07, damageType: "magic", spiritCost: 2 },
    durability: { max: 120, wearsOn: "combat" },
    effectSummary: "Magic two-hander. Dmg 9–14 · 2 Spirit / swing · 120 strikes.",
    onCraftedMessage: "👂 The Crozier is whole.",
    onBrokenMessage: "👂 The stone-head cracks free.",
    tier: 3, col: 25,
  },

  elementalBranch: {
    id: "elementalBranch", name: "Elemental Branch", icon: "🌿", category: "arcane",
    subfamily: "staff", discipline: "woodworking",
    description: "A long branch from a tree the wasteland was kind to. Still living, somehow.",
    cost: { fragments: 8, wood: 26, water: 10 },
    requires: { researched: "arcaneAwakening", studied: "stoneMend", builtBuilding: "alembic" },
    weaponStats: { type: "two-handed", damage: [6, 12], acc: 0.82, crit: 0.05, damageType: "magic", spiritCost: 2, hpReturn: 1 },
    durability: { max: 110, wearsOn: "combat" },
    effectSummary: "Magic two-hander. Dmg 6–12 · 2 Spirit / swing · +1 HP on hit · 110 strikes.",
    onCraftedMessage: "🌿 The Elemental Branch is finished. Still warm.",
    onBrokenMessage: "🌿 The branch goes dry.",
    tier: 3, col: 26,
  },

  lightbearerStaff: {
    id: "lightbearerStaff", name: "Lightbearer Staff", icon: "✨", category: "arcane",
    subfamily: "staff", discipline: "woodworking",
    description: "A tall staff with a small lantern of bound fragment-light at the head.",
    cost: { fragments: 10, wood: 20, stone: 12, ink: 5 },
    requires: { researched: "arcaneAwakening", studied: "greaterMending", builtBuilding: "alembic" },
    weaponStats: { type: "two-handed", damage: [7, 13], acc: 0.85, crit: 0.08, damageType: "magic", spiritCost: 2, demonBonus: 0.5 },
    durability: { max: 105, wearsOn: "combat" },
    effectSummary: "Magic two-hander. Dmg 7–13 · 2 Spirit / swing · +50% vs demons · 105 strikes.",
    onCraftedMessage: "✨ The Lightbearer Staff is whole. The lantern burns steady.",
    onBrokenMessage: "✨ The lantern winks out.",
    tier: 3, col: 27,
  },

  voidstaff: {
    id: "voidstaff", name: "Voidstaff", icon: "⚫", category: "arcane",
    subfamily: "staff", discipline: "woodworking",
    description: "A staff topped with a void-bound shard the eye refuses to follow.",
    cost: { fragments: 18, wood: 22, stone: 16, ink: 6, void_bone: 4, shadow_dust: 3, inverted_glyph: 1 },
    requires: { researched: "voidcall", builtBuilding: "alembic", alignment: { evil: 6 } },
    weaponStats: { type: "two-handed", damage: [12, 18], acc: 0.80, crit: 0.12, damageType: "magic", spiritCost: 4, sanityCost: 3 },
    durability: { max: 100, wearsOn: "combat" },
    effectSummary: "APEX magic two-hander. Dmg 12–18 · 4 Spirit + 3 Sanity / swing · 100 strikes.",
    onCraftedMessage: "⚫ The Voidstaff is bound. It is colder than thought.",
    onBrokenMessage: "⚫ The shard goes dark.",
    tier: 3, col: 28,
  },

  mendweaveWand: {
    id: "mendweaveWand", name: "Mendweave Wand", icon: "💗", category: "arcane",
    subfamily: "wand", discipline: "woodworking",
    description: "A short wand wrapped in fine cord etched with Light sigils.",
    cost: { fragments: 7, wood: 10, ink: 4 },
    requires: { researched: "arcaneAwakening", studied: "greaterMending", builtBuilding: "alembic" },
    weaponStats: { type: "melee", damage: [4, 8], acc: 0.88, crit: 0.10, damageType: "magic", spiritCost: 2, hpReturn: 2 },
    durability: { max: 90, wearsOn: "combat" },
    effectSummary: "Off-hand magic. Dmg 4–8 · 2 Spirit / swing · +2 HP on hit · 90 strikes.",
    onCraftedMessage: "💗 The Mendweave Wand is wrapped.",
    onBrokenMessage: "💗 The cord unravels.",
    tier: 3, col: 29,
  },

  bendwand: {
    id: "bendwand", name: "Bendwand", icon: "🌑", category: "arcane",
    subfamily: "wand", discipline: "woodworking",
    description: "A wand of dark-grained wood. Spells through it take a little; give it back to Spirit.",
    cost: { fragments: 8, wood: 8, stone: 6 },
    requires: { researched: "arcaneAwakening", studied: "greaterBend", builtBuilding: "alembic" },
    weaponStats: { type: "melee", damage: [5, 9], acc: 0.85, crit: 0.12, damageType: "magic", spiritReturn: 2 },
    durability: { max: 90, wearsOn: "combat" },
    effectSummary: "Off-hand magic. Dmg 5–9 · Crit 12% · +2 Spirit on hit · 90 strikes.",
    onCraftedMessage: "🌑 The Bendwand is finished.",
    onBrokenMessage: "🌑 The wand snaps.",
    tier: 3, col: 30,
  },

  soulflameWand: {
    id: "soulflameWand", name: "Soulflame Wand", icon: "🔥", category: "arcane",
    subfamily: "wand", discipline: "woodworking",
    description: "A wand tipped with a small ember of bound Bend-fire.",
    cost: { fragments: 9, wood: 8, stone: 8, food: 4 },
    requires: { researched: "arcaneAwakening", studied: "soulflame", builtBuilding: "alembic", alignment: { evil: 2 } },
    weaponStats: { type: "melee", damage: [6, 11], acc: 0.83, crit: 0.14, damageType: "magic", spiritCost: 2, sanityCost: 1 },
    durability: { max: 85, wearsOn: "combat" },
    effectSummary: "Off-hand magic. Dmg 6–11 · 2 Spirit + 1 Sanity / swing · 85 strikes.",
    onCraftedMessage: "🔥 The Soulflame Wand is bound. The ember does not flicker.",
    onBrokenMessage: "🔥 The ember goes out.",
    tier: 3, col: 31,
  },

  sigilcasterWand: {
    id: "sigilcasterWand", name: "Sigilcaster Wand", icon: "✒️", category: "arcane",
    subfamily: "wand", discipline: "woodworking",
    description: "A short, dense wand inscribed with the finest sigils.",
    cost: { fragments: 8, wood: 10, ink: 6 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic" },
    weaponStats: { type: "melee", damage: [4, 8], acc: 0.94, crit: 0.15, damageType: "magic", spiritCost: 1 },
    durability: { max: 95, wearsOn: "combat" },
    effectSummary: "Off-hand magic. Dmg 4–8 · Acc 94% · 1 Spirit / swing · 95 strikes.",
    onCraftedMessage: "✒️ The Sigilcaster Wand is whole.",
    onBrokenMessage: "✒️ The wand cracks.",
    tier: 3, col: 32,
  },

  echoWand: {
    id: "echoWand", name: "Echo Wand", icon: "👻", category: "arcane",
    subfamily: "wand", discipline: "woodworking",
    description: "A wand of pale wood that hums when held. Strikes return — faintly, a moment later.",
    cost: { fragments: 7, wood: 9, feathers: 3, ink: 3 },
    requires: { researched: "arcaneAwakening", studied: "ghostcall", builtBuilding: "alembic" },
    weaponStats: { type: "melee", damage: [5, 9], acc: 0.87, crit: 0.13, damageType: "magic", spiritCost: 2, echoChance: 0.25 },
    durability: { max: 90, wearsOn: "combat" },
    effectSummary: "Off-hand magic. Dmg 5–9 · 2 Spirit / swing · 25% chance to strike twice · 90 strikes.",
    onCraftedMessage: "👻 The Echo Wand is finished.",
    onBrokenMessage: "👻 The wand fades.",
    tier: 3, col: 33,
  },

  // ===== Consumables / Potions (Era 3, require Alembic built) =====

  potionMending: {
    id: "potionMending", name: "Potion of Mending", icon: "🧪",
    category: "consumable", consumable: true, isStackable: true,
    description: "Cloudy and warm. Tastes of stone.",
    cost: { fragments: 2, food: 5, water: 3 },
    requires: { researched: "alchemy", builtBuilding: "alembic" },
    useEffect: { hp: 40 },
    deathDebuffRecovery: 0.30,
    effectSummary: "Instant +40 HP. Strong death-debuff recovery.",
    onCraftedMessage: "🧪 A vial of Mending.",
    onUseMessage: "🧪 You drink the Mending. The body answers.",
    tier: 3, col: 3,
  },

  potionStillness: {
    id: "potionStillness", name: "Potion of Stillness", icon: "🫧",
    category: "consumable", consumable: true, isStackable: true,
    description: "Pale. Almost still.",
    cost: { fragments: 2, feathers: 5, water: 3 },
    requires: { researched: "alchemy", builtBuilding: "alembic" },
    useEffect: { sanity: 30 },
    effectSummary: "Instant +30 Sanity.",
    onCraftedMessage: "🫧 A vial of Stillness.",
    onUseMessage: "🫧 You drink the Stillness.",
    tier: 3, col: 4,
  },

  potionSpirit: {
    id: "potionSpirit", name: "Spirit Draught", icon: "💜",
    category: "consumable", consumable: true, isStackable: true,
    description: "Violet, almost humming.",
    cost: { fragments: 3, water: 10 },
    requires: { researched: "alchemy", builtBuilding: "alembic" },
    useEffect: { spirit: 100 },
    effectSummary: "Instant full Spirit.",
    onCraftedMessage: "💜 A Spirit Draught.",
    onUseMessage: "💜 You drink the Spirit Draught.",
    tier: 3, col: 5,
  },

  scrollCraft: {
    id: "scrollCraft", name: "Scroll", icon: "📜",
    category: "alchemy", isStackable: true, recipeFamily: "alchemy",
    description: "Beaten wood-fiber rolled thin.",
    cost: { wood: 2, fragments: 1 },
    requires: { researched: "altarWork" },
    producesResource: { id: "scroll", qty: 1 },
    effectSummary: "Craft +1 Scroll. Consumed at the Altar.",
    onCraftedMessage: "📜 You roll the parchment thin.",
    tier: 1, col: 0,
  },

  inkCraft: {
    id: "inkCraft", name: "Ink", icon: "🖋️",
    category: "alchemy", isStackable: true, recipeFamily: "alchemy",
    description: "Charred wood and crushed grub-dark.",
    cost: { wood: 1, food: 1 },
    requires: { researched: "altarWork" },
    producesResource: { id: "ink", qty: 1 },
    effectSummary: "Craft +1 Ink. Consumed at the Altar.",
    onCraftedMessage: "🖋️ You stir the ink.",
    tier: 1, col: 1,
  },

  // ─── Iron smelting (#36 / #131) — converts raw bog iron + wood fuel
  // into refined iron ingots at the Forge. The iron-tier weapons in
  // weapons.js (Iron Shortsword/Greatsword/etc.) consume the output.
  smeltIron: {
    id: "smeltIron", name: "Smelt Iron", icon: "🔩",
    category: "iron", isStackable: true, recipeFamily: "smithing",
    discipline: "blacksmithing",
    description: "Smelt bog ore over a hard fire. Pour. Cool. The shape that holds an edge.",
    cost: { bog_iron: 2, wood: 1 },
    requires: { researched: "smithing", builtBuilding: "forge" },
    producesResource: { id: "iron", qty: 1 },
    effectSummary: "Craft +1 Iron ingot. Consumed by iron-tier weapons + tools.",
    onCraftedMessage: "🔩 The ingot cools. The metal sings against the anvil.",
    tier: 3, col: 0,
  },

  // ─── Runesmithing recipes (#115) — bound runes for imbuing weapons or
  // burning as one-shot blessings. Each rune corresponds to a Study
  // path and demands the mob-drop that path's creatures yield.
  lightRuneCraft: {
    id: "lightRuneCraft", name: "Light Rune", icon: "✨",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "Inscribe a bound shard with a Light sigil. Held close, it warms. Imbued, it sings.",
    cost: { fragments: 2, ink: 1, cherub_feather: 1 },
    requires: { researched: "arcaneAwakening", studied: "greaterMending", builtBuilding: "alembic" },
    producesResource: { id: "lightRune", qty: 1 },
    effectSummary: "Craft +1 Light Rune. Use for healing-imbued gear or as a blessing.",
    onCraftedMessage: "✨ The Light Rune is whole. The sigil settles.",
    tier: 3, col: 0,
  },

  bendRuneCraft: {
    id: "bendRuneCraft", name: "Bend Rune", icon: "🌑",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A shard etched in dark-grained ink. The carving wants what isn't yours.",
    cost: { fragments: 2, ink: 1, corrupted_flesh: 1 },
    requires: { researched: "arcaneAwakening", studied: "greaterBend", builtBuilding: "alembic" },
    producesResource: { id: "bendRune", qty: 1 },
    effectSummary: "Craft +1 Bend Rune. Use for drain-imbued gear or as a blessing.",
    onCraftedMessage: "🌑 The Bend Rune is finished. The ink dries dark.",
    tier: 3, col: 1,
  },

  elementalRuneCraft: {
    id: "elementalRuneCraft", name: "Elemental Rune", icon: "🌿",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "Bound shard threaded with green ink. The wasteland answers it.",
    cost: { fragments: 2, ink: 1, pale_worm: 1, water: 3 },
    requires: { researched: "arcaneAwakening", studied: "stoneMend", builtBuilding: "alembic" },
    producesResource: { id: "elementalRune", qty: 1 },
    effectSummary: "Craft +1 Elemental Rune. Use for restoration-imbued gear.",
    onCraftedMessage: "🌿 The Elemental Rune is whole.",
    tier: 3, col: 2,
  },

  memoryRuneCraft: {
    id: "memoryRuneCraft", name: "Memory Rune", icon: "🔔",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A rune that holds the shape of what was lost.",
    cost: { fragments: 2, ink: 1, spirit_essence: 1 },
    requires: { researched: "arcaneAwakening", studied: "firstEcho", builtBuilding: "alembic" },
    producesResource: { id: "memoryRune", qty: 1 },
    effectSummary: "Craft +1 Memory Rune. Use for echo-imbued gear.",
    onCraftedMessage: "🔔 The Memory Rune is bound.",
    tier: 3, col: 3,
  },

  stonewordRuneCraft: {
    id: "stonewordRuneCraft", name: "Stoneword Rune", icon: "👂",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A rune that listens before it speaks. Heavy in the hand.",
    cost: { fragments: 2, ink: 1, void_bone: 1, stone: 3 },
    requires: { researched: "arcaneAwakening", studied: "firstStoneword", builtBuilding: "alembic" },
    producesResource: { id: "stonewordRune", qty: 1 },
    effectSummary: "Craft +1 Stoneword Rune. Use for durability-imbued gear.",
    onCraftedMessage: "👂 The Stoneword Rune is finished.",
    tier: 3, col: 4,
  },

  voidRuneCraft: {
    id: "voidRuneCraft", name: "Void Rune", icon: "⚫",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A rune carved from absent stone. The carving deepens when no one is looking.",
    cost: { fragments: 4, ink: 2, void_bone: 2, shadow_dust: 1 },
    requires: { researched: "voidcall", builtBuilding: "alembic", alignment: { evil: 4 } },
    producesResource: { id: "voidRune", qty: 1 },
    effectSummary: "Craft +1 Void Rune. APEX.",
    onCraftedMessage: "⚫ The Void Rune is bound.",
    tier: 3, col: 5,
  },

  // ─── Fletching arrows (#124) — stackable ammo. Pair with bow tier:
  // wood for primitive Bow, iron for the Iron Crossbow / Long/Shortbow,
  // shard for the arcane bows (Echo / Spiritsong / Lightweave / Sigil).
  woodArrows: {
    id: "woodArrows", name: "Wood Arrows", icon: "🏹",
    category: "primitive", isStackable: true, recipeFamily: "fletching",
    discipline: "fletching",
    description: "Knapped wood shafts with feather fletching. Cheap, plentiful, the first ammo.",
    cost: { wood: 3, feathers: 2 },
    requires: { researched: "fletching" },
    producesResource: { id: "arrows", qty: 5 },
    effectSummary: "Craft +5 Wood Arrows. Consumed by Bow / Shortbow / Longbow.",
    onCraftedMessage: "🏹 You fletch a quiver of arrows. The vanes sit even.",
    tier: 1, col: 0,
  },

  ironArrows: {
    id: "ironArrows", name: "Iron Arrows", icon: "🎯",
    category: "iron", isStackable: true, recipeFamily: "fletching",
    discipline: "fletching",
    description: "Iron-tipped shafts. Heavier draw, harder bite. Pairs with the Crossbow and iron-tier bows.",
    cost: { wood: 3, feathers: 2, iron: 2 },
    requires: { researched: "fletching", builtBuilding: "forge" },
    producesResource: { id: "ironArrows", qty: 5 },
    effectSummary: "Craft +5 Iron Arrows. Consumed by iron-tier ranged weapons.",
    onCraftedMessage: "🎯 You forge the heads, set the shafts. Iron rings against iron.",
    tier: 3, col: 1,
  },

  shardArrows: {
    id: "shardArrows", name: "Shard Arrows", icon: "✨",
    category: "arcane", isStackable: true, recipeFamily: "fletching",
    discipline: "fletching",
    description: "Arrows tipped with bound fragment-shards. They sing in the quiver. Pair with the arcane bows.",
    cost: { wood: 3, feathers: 2, fragments: 1 },
    requires: { researched: "arcaneAwakening", builtBuilding: "forge" },
    producesResource: { id: "shardArrows", qty: 5 },
    effectSummary: "Craft +5 Shard Arrows. Consumed by Era 3 arcane bows.",
    onCraftedMessage: "✨ You bind shard to shaft. The arrow hums.",
    tier: 3, col: 2,
  },

  // ─── #136 expanded rune recipes — 50 new craft recipes
  // matching the 50 new rune resources. Cost scales by rarity
  // (common → god); tier escalates duration + lowers base success.
  mendingChipCraft: {
    id: "mendingChipCraft", name: "Mending Chip", icon: "🩹",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A simple healing flake. Inscribe a Light glyph on a worn shard.",
    cost: { fragments: 1, ink: 1 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic" },
    producesResource: { id: "mendingChip", qty: 1 },
    effectSummary: "Craft +1 Mending Chip. Common rune.",
    onCraftedMessage: "🩹 The Mending Chip settles into shape.",
    rarity: "common",
    tier: 3, col: 0,
  },
  whisperChipCraft: {
    id: "whisperChipCraft", name: "Whisper Chip", icon: "🪶",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A small chip that hums to Spirit. Practice work for the Runesmith.",
    cost: { fragments: 1, ink: 1 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic" },
    producesResource: { id: "whisperChip", qty: 1 },
    effectSummary: "Craft +1 Whisper Chip. Common rune.",
    onCraftedMessage: "🪶 The Whisper Chip settles into shape.",
    rarity: "common",
    tier: 3, col: 1,
  },
  seedlingShardCraft: {
    id: "seedlingShardCraft", name: "Seedling Shard", icon: "🌱",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A green-veined shard for slow mending. The wasteland grants what it can.",
    cost: { fragments: 1, ink: 1, pale_worm: 1 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic" },
    producesResource: { id: "seedlingShard", qty: 1 },
    effectSummary: "Craft +1 Seedling Shard. Common rune.",
    onCraftedMessage: "🌱 The Seedling Shard settles into shape.",
    rarity: "common",
    tier: 3, col: 2,
  },
  truestrikeMarkCraft: {
    id: "truestrikeMarkCraft", name: "Truestrike Mark", icon: "🎯",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "An accuracy sigil. Cheap; reliable for the slow hand.",
    cost: { fragments: 1, ink: 1 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic" },
    producesResource: { id: "truestrikeMark", qty: 1 },
    effectSummary: "Craft +1 Truestrike Mark. Common rune.",
    onCraftedMessage: "🎯 The Truestrike Mark settles into shape.",
    rarity: "common",
    tier: 3, col: 3,
  },
  echoFragmentCraft: {
    id: "echoFragmentCraft", name: "Echo Fragment", icon: "🔉",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A faint memory-rune. A chip of the original Memory Rune.",
    cost: { fragments: 1, ink: 1 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic" },
    producesResource: { id: "echoFragment", qty: 1 },
    effectSummary: "Craft +1 Echo Fragment. Common rune.",
    onCraftedMessage: "🔉 The Echo Fragment settles into shape.",
    rarity: "common",
    tier: 3, col: 4,
  },
  pebbleWardCraft: {
    id: "pebbleWardCraft", name: "Pebble Ward", icon: "🪨",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A small ward etched in pebble. The metal lasts a little longer.",
    cost: { fragments: 1, ink: 1, stone: 2 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic" },
    producesResource: { id: "pebbleWard", qty: 1 },
    effectSummary: "Craft +1 Pebble Ward. Common rune.",
    onCraftedMessage: "🪨 The Pebble Ward settles into shape.",
    rarity: "common",
    tier: 3, col: 5,
  },
  splinterRuneCraft: {
    id: "splinterRuneCraft", name: "Splinter Rune", icon: "🥢",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A rune that wants to bite. Splinters of wood with an ink-edge.",
    cost: { fragments: 1, ink: 1, wood: 2 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic" },
    producesResource: { id: "splinterRune", qty: 1 },
    effectSummary: "Craft +1 Splinter Rune. Common rune.",
    onCraftedMessage: "🥢 The Splinter Rune settles into shape.",
    rarity: "common",
    tier: 3, col: 6,
  },
  emberRuneCraft: {
    id: "emberRuneCraft", name: "Ember Rune", icon: "🔥",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A faint heat-rune. The hand grips a little tighter.",
    cost: { fragments: 1, ink: 1 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic" },
    producesResource: { id: "emberRune", qty: 1 },
    effectSummary: "Craft +1 Ember Rune. Common rune.",
    onCraftedMessage: "🔥 The Ember Rune settles into shape.",
    rarity: "common",
    tier: 3, col: 7,
  },
  frostveinRuneCraft: {
    id: "frostveinRuneCraft", name: "Frostvein Rune", icon: "❄️",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A cold-blue line through a shard. Blunts incoming blows.",
    cost: { fragments: 2, ink: 1, pale_tendon: 1 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic" },
    producesResource: { id: "frostveinRune", qty: 1 },
    effectSummary: "Craft +1 Frostvein Rune. Uncommon rune.",
    onCraftedMessage: "❄️ The Frostvein Rune settles into shape.",
    rarity: "uncommon",
    tier: 3, col: 0,
  },
  horizonRuneCraft: {
    id: "horizonRuneCraft", name: "Horizon Rune", icon: "🌅",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A pale arc for accuracy and crit. Sigilcraft staple.",
    cost: { fragments: 2, ink: 1, shattered_glyph: 1 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic" },
    producesResource: { id: "horizonRune", qty: 1 },
    effectSummary: "Craft +1 Horizon Rune. Uncommon rune.",
    onCraftedMessage: "🌅 The Horizon Rune settles into shape.",
    rarity: "uncommon",
    tier: 3, col: 1,
  },
  radiantRuneCraft: {
    id: "radiantRuneCraft", name: "Radiant Rune", icon: "☀️",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A bright sigil that warms the bearer. Heals on hit, regen between.",
    cost: { fragments: 3, ink: 2, obol: 1, cherub_feather: 1 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic", studied: "greaterMending" },
    producesResource: { id: "radiantRune", qty: 1 },
    effectSummary: "Craft +1 Radiant Rune. Rare rune.",
    onCraftedMessage: "☀️ The Radiant Rune settles into shape.",
    rarity: "rare",
    tier: 3, col: 0,
  },
  nullingRuneCraft: {
    id: "nullingRuneCraft", name: "Nulling Rune", icon: "🌒",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A dark crescent that drinks Spirit and finds the soft place.",
    cost: { fragments: 3, ink: 2, obol: 1, corrupted_flesh: 1 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic", studied: "greaterBend" },
    producesResource: { id: "nullingRune", qty: 1 },
    effectSummary: "Craft +1 Nulling Rune. Rare rune.",
    onCraftedMessage: "🌒 The Nulling Rune settles into shape.",
    rarity: "rare",
    tier: 3, col: 1,
  },
  greenwoodRuneCraft: {
    id: "greenwoodRuneCraft", name: "Greenwood Rune", icon: "🌳",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A growing vein. Healing and bite together.",
    cost: { fragments: 3, ink: 2, obol: 1, pale_worm: 2 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic", studied: "stoneMend" },
    producesResource: { id: "greenwoodRune", qty: 1 },
    effectSummary: "Craft +1 Greenwood Rune. Rare rune.",
    onCraftedMessage: "🌳 The Greenwood Rune settles into shape.",
    rarity: "rare",
    tier: 3, col: 2,
  },
  inscribedSigilCraft: {
    id: "inscribedSigilCraft", name: "Inscribed Sigil", icon: "✒️",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A tight braid of ink-lines that finds the eye.",
    cost: { fragments: 3, ink: 2, obol: 1, shattered_glyph: 1 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic" },
    producesResource: { id: "inscribedSigil", qty: 1 },
    effectSummary: "Craft +1 Inscribed Sigil. Rare rune.",
    onCraftedMessage: "✒️ The Inscribed Sigil settles into shape.",
    rarity: "rare",
    tier: 3, col: 3,
  },
  mirrorEchoRuneCraft: {
    id: "mirrorEchoRuneCraft", name: "Mirror Echo Rune", icon: "🪞",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A polished shard that strikes back the way you came in.",
    cost: { fragments: 3, ink: 2, obol: 1, spirit_essence: 1 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic", studied: "firstEcho" },
    producesResource: { id: "mirrorEchoRune", qty: 1 },
    effectSummary: "Craft +1 Mirror Echo Rune. Rare rune.",
    onCraftedMessage: "🪞 The Mirror Echo Rune settles into shape.",
    rarity: "rare",
    tier: 3, col: 4,
  },
  bedrockRuneCraft: {
    id: "bedrockRuneCraft", name: "Bedrock Rune", icon: "⛰️",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A heavy chunk of inscribed bedrock. Holds gear together.",
    cost: { fragments: 3, ink: 2, obol: 1, void_bone: 1, stone: 4 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic", studied: "firstStoneword" },
    producesResource: { id: "bedrockRune", qty: 1 },
    effectSummary: "Craft +1 Bedrock Rune. Rare rune.",
    onCraftedMessage: "⛰️ The Bedrock Rune settles into shape.",
    rarity: "rare",
    tier: 3, col: 5,
  },
  ravenousVoidRuneCraft: {
    id: "ravenousVoidRuneCraft", name: "Ravenous Void Rune", icon: "🕳️",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A hungry shard. The hand pays for swings.",
    cost: { fragments: 3, ink: 2, obol: 1, void_bone: 1, shadow_dust: 1 },
    requires: { researched: "voidcall", builtBuilding: "alembic", alignment: { evil: 2 } },
    producesResource: { id: "ravenousVoidRune", qty: 1 },
    effectSummary: "Craft +1 Ravenous Void Rune. Rare rune.",
    onCraftedMessage: "🕳️ The Ravenous Void Rune settles into shape.",
    rarity: "rare",
    tier: 3, col: 6,
  },
  huntermarkRuneCraft: {
    id: "huntermarkRuneCraft", name: "Huntermark Rune", icon: "🦌",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A predator's sigil. Steady. Hungry.",
    cost: { fragments: 3, ink: 2, obol: 1, tusks: 1 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic" },
    producesResource: { id: "huntermarkRune", qty: 1 },
    effectSummary: "Craft +1 Huntermark Rune. Rare rune.",
    onCraftedMessage: "🦌 The Huntermark Rune settles into shape.",
    rarity: "rare",
    tier: 3, col: 7,
  },
  searingRuneCraft: {
    id: "searingRuneCraft", name: "Searing Rune", icon: "🌞",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A burn-rune. Heals you, scorches them.",
    cost: { fragments: 5, ink: 3, obol: 2, cherub_feather: 2 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic", studied: "cleansingWord" },
    producesResource: { id: "searingRune", qty: 1 },
    effectSummary: "Craft +1 Searing Rune. Epic rune.",
    onCraftedMessage: "🌞 The Searing Rune settles into shape.",
    rarity: "epic",
    tier: 4, col: 0,
  },
  chasmRuneCraft: {
    id: "chasmRuneCraft", name: "Chasm Rune", icon: "🌑",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A rune that reaches down and pulls Spirit up.",
    cost: { fragments: 5, ink: 3, obol: 2, corrupted_flesh: 2, spirit_essence: 1 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic", studied: "curse" },
    producesResource: { id: "chasmRune", qty: 1 },
    effectSummary: "Craft +1 Chasm Rune. Epic rune.",
    onCraftedMessage: "🌑 The Chasm Rune settles into shape.",
    rarity: "epic",
    tier: 4, col: 1,
  },
  worldrootRuneCraft: {
    id: "worldrootRuneCraft", name: "Worldroot Rune", icon: "🌲",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "Roots threaded through stone. Stable and lethal.",
    cost: { fragments: 5, ink: 3, obol: 2, pale_worm: 3 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic", studied: "stoneMend" },
    producesResource: { id: "worldrootRune", qty: 1 },
    effectSummary: "Craft +1 Worldroot Rune. Epic rune.",
    onCraftedMessage: "🌲 The Worldroot Rune settles into shape.",
    rarity: "epic",
    tier: 4, col: 2,
  },
  masterSigilCraft: {
    id: "masterSigilCraft", name: "Master Sigil", icon: "📐",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A sigil drawn by a hand that knows its own.",
    cost: { fragments: 5, ink: 3, obol: 2, shattered_glyph: 2, inverted_glyph: 1 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic" },
    producesResource: { id: "masterSigil", qty: 1 },
    effectSummary: "Craft +1 Master Sigil. Epic rune.",
    onCraftedMessage: "📐 The Master Sigil settles into shape.",
    rarity: "epic",
    tier: 4, col: 3,
  },
  temporalRuneCraft: {
    id: "temporalRuneCraft", name: "Temporal Rune", icon: "⌛",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A rune that argues with the second-hand.",
    cost: { fragments: 5, ink: 3, obol: 2, spirit_essence: 2 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic", studied: "ghostcall" },
    producesResource: { id: "temporalRune", qty: 1 },
    effectSummary: "Craft +1 Temporal Rune. Epic rune.",
    onCraftedMessage: "⌛ The Temporal Rune settles into shape.",
    rarity: "epic",
    tier: 4, col: 4,
  },
  monolithRuneCraft: {
    id: "monolithRuneCraft", name: "Monolith Rune", icon: "🗿",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A rune the size of a fist. The weapon doesn't dare break.",
    cost: { fragments: 5, ink: 3, obol: 2, void_bone: 2, stone: 8 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic", studied: "firstStoneword" },
    producesResource: { id: "monolithRune", qty: 1 },
    effectSummary: "Craft +1 Monolith Rune. Epic rune.",
    onCraftedMessage: "🗿 The Monolith Rune settles into shape.",
    rarity: "epic",
    tier: 4, col: 5,
  },
  malignVoidRuneCraft: {
    id: "malignVoidRuneCraft", name: "Malign Void Rune", icon: "👁️",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A rune that watches you. Strikes harder for it.",
    cost: { fragments: 5, ink: 3, obol: 2, void_bone: 2, lidless_eye: 1 },
    requires: { researched: "voidcall", builtBuilding: "alembic", alignment: { evil: 4 } },
    producesResource: { id: "malignVoidRune", qty: 1 },
    effectSummary: "Craft +1 Malign Void Rune. Epic rune.",
    onCraftedMessage: "👁️ The Malign Void Rune settles into shape.",
    rarity: "epic",
    tier: 4, col: 6,
  },
  sunkenRuneCraft: {
    id: "sunkenRuneCraft", name: "Sunken Rune", icon: "🌊",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A rune pulled from a flooded shrine. Both blade and balm.",
    cost: { fragments: 5, ink: 3, obol: 2, hollow_garment: 1, water: 5 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic" },
    producesResource: { id: "sunkenRune", qty: 1 },
    effectSummary: "Craft +1 Sunken Rune. Epic rune.",
    onCraftedMessage: "🌊 The Sunken Rune settles into shape.",
    rarity: "epic",
    tier: 4, col: 7,
  },
  dawnbreakerCraft: {
    id: "dawnbreakerCraft", name: "Dawnbreaker Rune", icon: "🌄",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A rune of the first light. Heals through anything.",
    cost: { fragments: 8, ink: 5, obol: 3, cherub_feather: 3 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic", studied: "blessing" },
    producesResource: { id: "dawnbreaker", qty: 1 },
    effectSummary: "Craft +1 Dawnbreaker Rune. Legendary rune.",
    onCraftedMessage: "🌄 The Dawnbreaker Rune settles into shape.",
    rarity: "legendary",
    tier: 4, col: 0,
  },
  chasmlordRuneCraft: {
    id: "chasmlordRuneCraft", name: "Chasmlord Rune", icon: "🌌",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A rune that holds the chasm. Spirit pours from it.",
    cost: { fragments: 8, ink: 5, obol: 3, corrupted_flesh: 3, spirit_essence: 2 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic", studied: "dominate" },
    producesResource: { id: "chasmlordRune", qty: 1 },
    effectSummary: "Craft +1 Chasmlord Rune. Legendary rune.",
    onCraftedMessage: "🌌 The Chasmlord Rune settles into shape.",
    rarity: "legendary",
    tier: 4, col: 1,
  },
  gaiaRuneCraft: {
    id: "gaiaRuneCraft", name: "Gaia Rune", icon: "🌍",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A rune carved into living stone. The world is on your side.",
    cost: { fragments: 8, ink: 5, obol: 3, pale_worm: 4, pale_tendon: 2 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic", studied: "stoneMend" },
    producesResource: { id: "gaiaRune", qty: 1 },
    effectSummary: "Craft +1 Gaia Rune. Legendary rune.",
    onCraftedMessage: "🌍 The Gaia Rune settles into shape.",
    rarity: "legendary",
    tier: 4, col: 2,
  },
  archmageSigilCraft: {
    id: "archmageSigilCraft", name: "Archmage Sigil", icon: "🔮",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A sigil bound by a name no one remembers.",
    cost: { fragments: 8, ink: 5, obol: 3, shattered_glyph: 3, inverted_glyph: 2 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic" },
    producesResource: { id: "archmageSigil", qty: 1 },
    effectSummary: "Craft +1 Archmage Sigil. Legendary rune.",
    onCraftedMessage: "🔮 The Archmage Sigil settles into shape.",
    rarity: "legendary",
    tier: 4, col: 3,
  },
  echofallRuneCraft: {
    id: "echofallRuneCraft", name: "Echofall Rune", icon: "🎐",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A rune that lets the strike fall twice.",
    cost: { fragments: 8, ink: 5, obol: 3, spirit_essence: 3, wax_mask: 1 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic", studied: "echo" },
    producesResource: { id: "echofallRune", qty: 1 },
    effectSummary: "Craft +1 Echofall Rune. Legendary rune.",
    onCraftedMessage: "🎐 The Echofall Rune settles into shape.",
    rarity: "legendary",
    tier: 4, col: 4,
  },
  worldstoneRuneCraft: {
    id: "worldstoneRuneCraft", name: "Worldstone Rune", icon: "💎",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A rune cut from the lowest layer. Nothing breaks.",
    cost: { fragments: 8, ink: 5, obol: 3, void_bone: 3, iron: 5 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic", studied: "firstStoneword" },
    producesResource: { id: "worldstoneRune", qty: 1 },
    effectSummary: "Craft +1 Worldstone Rune. Legendary rune.",
    onCraftedMessage: "💎 The Worldstone Rune settles into shape.",
    rarity: "legendary",
    tier: 4, col: 5,
  },
  nullVoidRuneCraft: {
    id: "nullVoidRuneCraft", name: "Null Void Rune", icon: "♾️",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A rune that says the word for absence and means it.",
    cost: { fragments: 8, ink: 5, obol: 3, void_bone: 3, shadow_dust: 2, lidless_eye: 1 },
    requires: { researched: "voidcall", builtBuilding: "alembic", alignment: { evil: 6 } },
    producesResource: { id: "nullVoidRune", qty: 1 },
    effectSummary: "Craft +1 Null Void Rune. Legendary rune.",
    onCraftedMessage: "♾️ The Null Void Rune settles into shape.",
    rarity: "legendary",
    tier: 4, col: 6,
  },
  starforgeRuneCraft: {
    id: "starforgeRuneCraft", name: "Starforge Rune", icon: "⭐",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "Forged in a place where stars die. The strike crits like one.",
    cost: { fragments: 8, ink: 5, obol: 3, starlit_fragment: 1 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic" },
    producesResource: { id: "starforgeRune", qty: 1 },
    effectSummary: "Craft +1 Starforge Rune. Legendary rune.",
    onCraftedMessage: "⭐ The Starforge Rune settles into shape.",
    rarity: "legendary",
    tier: 4, col: 7,
  },
  sunlordRuneCraft: {
    id: "sunlordRuneCraft", name: "Sunlord Rune", icon: "🌟",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A rune that wears the noon sky.",
    cost: { fragments: 15, ink: 8, obol: 5, cherub_feather: 4, starlit_fragment: 1 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic", studied: "blessing" },
    producesResource: { id: "sunlordRune", qty: 1 },
    effectSummary: "Craft +1 Sunlord Rune. Mythic rune.",
    onCraftedMessage: "🌟 The Sunlord Rune settles into shape.",
    rarity: "mythic",
    tier: 4, col: 0,
  },
  abyssalRuneCraft: {
    id: "abyssalRuneCraft", name: "Abyssal Rune", icon: "🌀",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A rune that learned to drown. Spirit is yours and not.",
    cost: { fragments: 15, ink: 8, obol: 5, corrupted_flesh: 5, spirit_essence: 3, lidless_eye: 1 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic", studied: "dominate" },
    producesResource: { id: "abyssalRune", qty: 1 },
    effectSummary: "Craft +1 Abyssal Rune. Mythic rune.",
    onCraftedMessage: "🌀 The Abyssal Rune settles into shape.",
    rarity: "mythic",
    tier: 4, col: 1,
  },
  worldheartRuneCraft: {
    id: "worldheartRuneCraft", name: "Worldheart Rune", icon: "❤️‍🔥",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "Forged in the heart of the world. Everything obeys.",
    cost: { fragments: 15, ink: 8, obol: 5, pale_worm: 6, pale_tendon: 3, starlit_fragment: 1 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic" },
    producesResource: { id: "worldheartRune", qty: 1 },
    effectSummary: "Craft +1 Worldheart Rune. Mythic rune.",
    onCraftedMessage: "❤️‍🔥 The Worldheart Rune settles into shape.",
    rarity: "mythic",
    tier: 4, col: 2,
  },
  runelordSigilCraft: {
    id: "runelordSigilCraft", name: "Runelord Sigil", icon: "🪄",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "The sigil of the one who taught all sigils.",
    cost: { fragments: 15, ink: 8, obol: 5, shattered_glyph: 5, inverted_glyph: 3 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic" },
    producesResource: { id: "runelordSigil", qty: 1 },
    effectSummary: "Craft +1 Runelord Sigil. Mythic rune.",
    onCraftedMessage: "🪄 The Runelord Sigil settles into shape.",
    rarity: "mythic",
    tier: 4, col: 3,
  },
  timewovenRuneCraft: {
    id: "timewovenRuneCraft", name: "Timewoven Rune", icon: "⏳",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A rune that braids the second and the next.",
    cost: { fragments: 15, ink: 8, obol: 5, spirit_essence: 5, wax_mask: 2 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic", studied: "ghostcall" },
    producesResource: { id: "timewovenRune", qty: 1 },
    effectSummary: "Craft +1 Timewoven Rune. Mythic rune.",
    onCraftedMessage: "⏳ The Timewoven Rune settles into shape.",
    rarity: "mythic",
    tier: 4, col: 4,
  },
  bedrocklordRuneCraft: {
    id: "bedrocklordRuneCraft", name: "Bedrocklord Rune", icon: "🏔️",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A rune that owns the floor of the world.",
    cost: { fragments: 15, ink: 8, obol: 5, void_bone: 5, iron: 10 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic", studied: "firstStoneword" },
    producesResource: { id: "bedrocklordRune", qty: 1 },
    effectSummary: "Craft +1 Bedrocklord Rune. Mythic rune.",
    onCraftedMessage: "🏔️ The Bedrocklord Rune settles into shape.",
    rarity: "mythic",
    tier: 4, col: 5,
  },
  annihilateRuneCraft: {
    id: "annihilateRuneCraft", name: "Annihilation Rune", icon: "💥",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A rune that says: nothing remains.",
    cost: { fragments: 15, ink: 8, obol: 5, void_bone: 4, shadow_dust: 3, lidless_eye: 2 },
    requires: { researched: "voidcall", builtBuilding: "alembic", alignment: { evil: 8 } },
    producesResource: { id: "annihilateRune", qty: 1 },
    effectSummary: "Craft +1 Annihilation Rune. Mythic rune.",
    onCraftedMessage: "💥 The Annihilation Rune settles into shape.",
    rarity: "mythic",
    tier: 4, col: 6,
  },
  soulreaverRuneCraft: {
    id: "soulreaverRuneCraft", name: "Soulreaver Rune", icon: "💀",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "A rune that drinks. The blade is fed.",
    cost: { fragments: 15, ink: 8, obol: 5, corrupted_flesh: 4, spirit_essence: 4, hollow_garment: 2 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic", studied: "soulflame" },
    producesResource: { id: "soulreaverRune", qty: 1 },
    effectSummary: "Craft +1 Soulreaver Rune. Mythic rune.",
    onCraftedMessage: "💀 The Soulreaver Rune settles into shape.",
    rarity: "mythic",
    tier: 4, col: 7,
  },
  godrune_sunCraft: {
    id: "godrune_sunCraft", name: "Godrune of the Sun", icon: "🌞",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "The Sun's own rune.",
    cost: { fragments: 30, ink: 15, obol: 10, cherub_feather: 8, starlit_fragment: 3 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic", studied: "blessing", alignment: { good: 6 } },
    producesResource: { id: "godrune_ofTheSun", qty: 1 },
    effectSummary: "Craft +1 Godrune of the Sun. God rune.",
    onCraftedMessage: "🌞 The Godrune of the Sun settles into shape.",
    rarity: "god",
    tier: 4, col: 0,
  },
  godrune_bendCraft: {
    id: "godrune_bendCraft", name: "Godrune of the Bend", icon: "🌑",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "The Moon's own rune.",
    cost: { fragments: 30, ink: 15, obol: 10, corrupted_flesh: 10, spirit_essence: 6, starlit_fragment: 2 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic", studied: "dominate", alignment: { evil: 6 } },
    producesResource: { id: "godrune_ofTheBend", qty: 1 },
    effectSummary: "Craft +1 Godrune of the Bend. God rune.",
    onCraftedMessage: "🌑 The Godrune of the Bend settles into shape.",
    rarity: "god",
    tier: 4, col: 1,
  },
  godrune_worldCraft: {
    id: "godrune_worldCraft", name: "Godrune of the World", icon: "🌐",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "The world's name in rune-form.",
    cost: { fragments: 30, ink: 15, obol: 10, pale_worm: 12, pale_tendon: 6, starlit_fragment: 3 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic" },
    producesResource: { id: "godrune_ofTheWorld", qty: 1 },
    effectSummary: "Craft +1 Godrune of the World. God rune.",
    onCraftedMessage: "🌐 The Godrune of the World settles into shape.",
    rarity: "god",
    tier: 4, col: 2,
  },
  godrune_sigilCraft: {
    id: "godrune_sigilCraft", name: "Godrune of the Sigil", icon: "🪐",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "The rune that ends all rune-arguments.",
    cost: { fragments: 30, ink: 15, obol: 10, shattered_glyph: 10, inverted_glyph: 6, starlit_fragment: 2 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic" },
    producesResource: { id: "godrune_ofTheSigil", qty: 1 },
    effectSummary: "Craft +1 Godrune of the Sigil. God rune.",
    onCraftedMessage: "🪐 The Godrune of the Sigil settles into shape.",
    rarity: "god",
    tier: 4, col: 3,
  },
  godrune_voidCraft: {
    id: "godrune_voidCraft", name: "Godrune of the Void", icon: "⚫",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "The rune that knows what nothing means.",
    cost: { fragments: 30, ink: 15, obol: 10, void_bone: 10, shadow_dust: 6, lidless_eye: 4, starlit_fragment: 3 },
    requires: { researched: "voidcall", builtBuilding: "alembic", alignment: { evil: 10 } },
    producesResource: { id: "godrune_ofTheVoid", qty: 1 },
    effectSummary: "Craft +1 Godrune of the Void. God rune.",
    onCraftedMessage: "⚫ The Godrune of the Void settles into shape.",
    rarity: "god",
    tier: 4, col: 4,
  },
  godrune_stoneCraft: {
    id: "godrune_stoneCraft", name: "Godrune of the Stone", icon: "🗿",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "The first rune the world ever made.",
    cost: { fragments: 30, ink: 15, obol: 10, void_bone: 8, iron: 20, starlit_fragment: 2 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic", studied: "firstStoneword" },
    producesResource: { id: "godrune_ofTheStone", qty: 1 },
    effectSummary: "Craft +1 Godrune of the Stone. God rune.",
    onCraftedMessage: "🗿 The Godrune of the Stone settles into shape.",
    rarity: "god",
    tier: 4, col: 5,
  },
  godrune_memoryCraft: {
    id: "godrune_memoryCraft", name: "Godrune of Memory", icon: "🔔",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "The rune that holds every echo ever made.",
    cost: { fragments: 30, ink: 15, obol: 10, spirit_essence: 10, wax_mask: 5, starlit_fragment: 3 },
    requires: { researched: "arcaneAwakening", builtBuilding: "alembic", studied: "ghostcall" },
    producesResource: { id: "godrune_ofMemory", qty: 1 },
    effectSummary: "Craft +1 Godrune of Memory. God rune.",
    onCraftedMessage: "🔔 The Godrune of Memory settles into shape.",
    rarity: "god",
    tier: 4, col: 6,
  },
  godrune_oblivionCraft: {
    id: "godrune_oblivionCraft", name: "Godrune of Oblivion", icon: "🩸",
    category: "alchemy", isStackable: true, recipeFamily: "runesmithing",
    discipline: "runesmithing",
    description: "The last rune. The apex.",
    cost: { fragments: 30, ink: 15, obol: 10, void_bone: 15, shadow_dust: 10, lidless_eye: 6, starlit_fragment: 5 },
    requires: { researched: "voidcall", builtBuilding: "alembic", alignment: { evil: 12 } },
    producesResource: { id: "godrune_oblivion", qty: 1 },
    effectSummary: "Craft +1 Godrune of Oblivion. God rune.",
    onCraftedMessage: "🩸 The Godrune of Oblivion settles into shape.",
    rarity: "god",
    tier: 4, col: 7,
  },
};

export const getTool = (id) => TOOLS[id] || null;
export const getAllTools = () => Object.values(TOOLS);

export function getToolEffects(run) {
  const eff = {
    gatherBonus: 0, gatherSpeedup: 0, waterBonus: 0, woodBonus: 0,
    stoneBonus: 0, foodBonus: 0, huntYieldBonus: 0,
    huntCooldownReduction: 0, huntBetterBirds: 0, spiritPerMinute: 0,
    sanityPerFoodGather: 0, demonDamageMult: 1, demonSanityMult: 1,
  };
  for (const tool of Object.values(TOOLS)) {
    if (!(run.inventory?.[tool.id] > 0)) continue;
    const e = tool.effect;
    if (!e) continue;
    if (e.gatherBonus) eff.gatherBonus += e.gatherBonus;
    if (e.gatherSpeedup) eff.gatherSpeedup += e.gatherSpeedup;
    if (e.waterBonus) eff.waterBonus += e.waterBonus;
    if (e.woodBonus) eff.woodBonus += e.woodBonus;
    if (e.stoneBonus) eff.stoneBonus += e.stoneBonus;
    if (e.foodBonus) eff.foodBonus += e.foodBonus;
    if (e.huntYieldBonus) eff.huntYieldBonus += e.huntYieldBonus;
    if (e.huntCooldownReduction) eff.huntCooldownReduction += e.huntCooldownReduction;
    if (e.huntBetterBirds) eff.huntBetterBirds += e.huntBetterBirds;
    if (e.spiritPerMinute) eff.spiritPerMinute += e.spiritPerMinute;
    if (e.sanityPerFoodGather) eff.sanityPerFoodGather += e.sanityPerFoodGather;
    if (typeof e.demonDamageMult === "number") eff.demonDamageMult *= e.demonDamageMult;
    if (typeof e.demonSanityMult === "number") eff.demonSanityMult *= e.demonSanityMult;
  }
  return eff;
}

// ─── Producer lookup (#128) — given a resource id, return the TOOL
// recipe that produces it (via producesResource).
export function getProducerForResource(resourceId) {
  for (const tool of Object.values(TOOLS)) {
    if (tool.producesResource?.id === resourceId) return tool;
  }
  return null;
}

export function getToolDiscipline(tool) {
  if (!tool) return "blacksmithing";
  if (tool.discipline) return tool.discipline;
  if (tool.category === "consumable" || tool.category === "alchemy") return "alchemy";
  if (tool.id === "bow") return "fletching";
  if (tool.id === "net" || tool.id === "snare" || tool.id === "waterSkin"
      || tool.id === "diggingStick" || tool.id === "wardingTalisman") {
    return "survivalcraft";
  }
  if (tool.id === "spiritCenser") return "alchemy";
  return "blacksmithing";
}
